// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gqlgen-crud/ent/member"
	"gqlgen-crud/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	memberFields := schema.Member{}.Fields()
	_ = memberFields
	// memberDescName is the schema descriptor for name field.
	memberDescName := memberFields[1].Descriptor()
	// member.DefaultName holds the default value on creation for the name field.
	member.DefaultName = memberDescName.Default.(string)
	// memberDescNick is the schema descriptor for nick field.
	memberDescNick := memberFields[2].Descriptor()
	// member.DefaultNick holds the default value on creation for the nick field.
	member.DefaultNick = memberDescNick.Default.(string)
	// memberDescTeam is the schema descriptor for team field.
	memberDescTeam := memberFields[3].Descriptor()
	// member.DefaultTeam holds the default value on creation for the team field.
	member.DefaultTeam = memberDescTeam.Default.(string)
	// memberDescDetail is the schema descriptor for detail field.
	memberDescDetail := memberFields[4].Descriptor()
	// member.DefaultDetail holds the default value on creation for the detail field.
	member.DefaultDetail = memberDescDetail.Default.(string)
	// memberDescImg is the schema descriptor for img field.
	memberDescImg := memberFields[5].Descriptor()
	// member.DefaultImg holds the default value on creation for the img field.
	member.DefaultImg = memberDescImg.Default.(string)
}
