// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type MemberInput struct {
	ID     *int   `json:"id"`
	Name   string `json:"name"`
	Nick   string `json:"nick"`
	Team   string `json:"team"`
	Detail string `json:"detail"`
	Img    string `json:"img"`
}
