// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"io"
	"odin/ent/artist"
	"odin/ent/menu"
	"odin/ent/partnership"
	"odin/ent/store"
	"odin/ent/user"
	"strconv"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/errcode"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"github.com/vmihailenco/msgpack/v5"
)

// OrderDirection defines the directions in which to order a list of items.
type OrderDirection string

const (
	// OrderDirectionAsc specifies an ascending order.
	OrderDirectionAsc OrderDirection = "ASC"
	// OrderDirectionDesc specifies a descending order.
	OrderDirectionDesc OrderDirection = "DESC"
)

// Validate the order direction value.
func (o OrderDirection) Validate() error {
	if o != OrderDirectionAsc && o != OrderDirectionDesc {
		return fmt.Errorf("%s is not a valid OrderDirection", o)
	}
	return nil
}

// String implements fmt.Stringer interface.
func (o OrderDirection) String() string {
	return string(o)
}

// MarshalGQL implements graphql.Marshaler interface.
func (o OrderDirection) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(o.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (o *OrderDirection) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("order direction %T must be a string", val)
	}
	*o = OrderDirection(str)
	return o.Validate()
}

func (o OrderDirection) reverse() OrderDirection {
	if o == OrderDirectionDesc {
		return OrderDirectionAsc
	}
	return OrderDirectionDesc
}

func (o OrderDirection) orderFunc(field string) OrderFunc {
	if o == OrderDirectionDesc {
		return Desc(field)
	}
	return Asc(field)
}

func cursorsToPredicates(direction OrderDirection, after, before *Cursor, field, idField string) []func(s *sql.Selector) {
	var predicates []func(s *sql.Selector)
	if after != nil {
		if after.Value != nil {
			var predicate func([]string, ...interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.CompositeGT
			} else {
				predicate = sql.CompositeLT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.Columns(field, idField),
					after.Value, after.ID,
				))
			})
		} else {
			var predicate func(string, interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.GT
			} else {
				predicate = sql.LT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.C(idField),
					after.ID,
				))
			})
		}
	}
	if before != nil {
		if before.Value != nil {
			var predicate func([]string, ...interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.CompositeLT
			} else {
				predicate = sql.CompositeGT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.Columns(field, idField),
					before.Value, before.ID,
				))
			})
		} else {
			var predicate func(string, interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.LT
			} else {
				predicate = sql.GT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.C(idField),
					before.ID,
				))
			})
		}
	}
	return predicates
}

// PageInfo of a connection type.
type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *Cursor `json:"startCursor"`
	EndCursor       *Cursor `json:"endCursor"`
}

// Cursor of an edge type.
type Cursor struct {
	ID    int   `msgpack:"i"`
	Value Value `msgpack:"v,omitempty"`
}

// MarshalGQL implements graphql.Marshaler interface.
func (c Cursor) MarshalGQL(w io.Writer) {
	quote := []byte{'"'}
	w.Write(quote)
	defer w.Write(quote)
	wc := base64.NewEncoder(base64.RawStdEncoding, w)
	defer wc.Close()
	_ = msgpack.NewEncoder(wc).Encode(c)
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (c *Cursor) UnmarshalGQL(v interface{}) error {
	s, ok := v.(string)
	if !ok {
		return fmt.Errorf("%T is not a string", v)
	}
	if err := msgpack.NewDecoder(
		base64.NewDecoder(
			base64.RawStdEncoding,
			strings.NewReader(s),
		),
	).Decode(c); err != nil {
		return fmt.Errorf("cannot decode cursor: %w", err)
	}
	return nil
}

const errInvalidPagination = "INVALID_PAGINATION"

func validateFirstLast(first, last *int) (err *gqlerror.Error) {
	switch {
	case first != nil && last != nil:
		err = &gqlerror.Error{
			Message: "Passing both `first` and `last` to paginate a connection is not supported.",
		}
	case first != nil && *first < 0:
		err = &gqlerror.Error{
			Message: "`first` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	case last != nil && *last < 0:
		err = &gqlerror.Error{
			Message: "`last` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	}
	return err
}

func collectedField(ctx context.Context, path ...string) *graphql.CollectedField {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return nil
	}
	field := fc.Field
	oc := graphql.GetOperationContext(ctx)
walk:
	for _, name := range path {
		for _, f := range graphql.CollectFields(oc, field.Selections, nil) {
			if f.Name == name {
				field = f
				continue walk
			}
		}
		return nil
	}
	return &field
}

func hasCollectedField(ctx context.Context, path ...string) bool {
	if graphql.GetFieldContext(ctx) == nil {
		return true
	}
	return collectedField(ctx, path...) != nil
}

const (
	edgesField      = "edges"
	nodeField       = "node"
	pageInfoField   = "pageInfo"
	totalCountField = "totalCount"
)

func paginateLimit(first, last *int) int {
	var limit int
	if first != nil {
		limit = *first + 1
	} else if last != nil {
		limit = *last + 1
	}
	return limit
}

// ArtistEdge is the edge representation of Artist.
type ArtistEdge struct {
	Node   *Artist `json:"node"`
	Cursor Cursor  `json:"cursor"`
}

// ArtistConnection is the connection containing edges to Artist.
type ArtistConnection struct {
	Edges      []*ArtistEdge `json:"edges"`
	PageInfo   PageInfo      `json:"pageInfo"`
	TotalCount int           `json:"totalCount"`
}

func (c *ArtistConnection) build(nodes []*Artist, pager *artistPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *Artist
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Artist {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Artist {
			return nodes[i]
		}
	}
	c.Edges = make([]*ArtistEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &ArtistEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// ArtistPaginateOption enables pagination customization.
type ArtistPaginateOption func(*artistPager) error

// WithArtistOrder configures pagination ordering.
func WithArtistOrder(order *ArtistOrder) ArtistPaginateOption {
	if order == nil {
		order = DefaultArtistOrder
	}
	o := *order
	return func(pager *artistPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultArtistOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithArtistFilter configures pagination filter.
func WithArtistFilter(filter func(*ArtistQuery) (*ArtistQuery, error)) ArtistPaginateOption {
	return func(pager *artistPager) error {
		if filter == nil {
			return errors.New("ArtistQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type artistPager struct {
	order  *ArtistOrder
	filter func(*ArtistQuery) (*ArtistQuery, error)
}

func newArtistPager(opts []ArtistPaginateOption) (*artistPager, error) {
	pager := &artistPager{}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultArtistOrder
	}
	return pager, nil
}

func (p *artistPager) applyFilter(query *ArtistQuery) (*ArtistQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *artistPager) toCursor(a *Artist) Cursor {
	return p.order.Field.toCursor(a)
}

func (p *artistPager) applyCursors(query *ArtistQuery, after, before *Cursor) *ArtistQuery {
	for _, predicate := range cursorsToPredicates(
		p.order.Direction, after, before,
		p.order.Field.field, DefaultArtistOrder.Field.field,
	) {
		query = query.Where(predicate)
	}
	return query
}

func (p *artistPager) applyOrder(query *ArtistQuery, reverse bool) *ArtistQuery {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	query = query.Order(direction.orderFunc(p.order.Field.field))
	if p.order.Field != DefaultArtistOrder.Field {
		query = query.Order(direction.orderFunc(DefaultArtistOrder.Field.field))
	}
	return query
}

func (p *artistPager) orderExpr(reverse bool) sql.Querier {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.field).Pad().WriteString(string(direction))
		if p.order.Field != DefaultArtistOrder.Field {
			b.Comma().Ident(DefaultArtistOrder.Field.field).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to Artist.
func (a *ArtistQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...ArtistPaginateOption,
) (*ArtistConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newArtistPager(opts)
	if err != nil {
		return nil, err
	}
	if a, err = pager.applyFilter(a); err != nil {
		return nil, err
	}
	conn := &ArtistConnection{Edges: []*ArtistEdge{}}
	if !hasCollectedField(ctx, edgesField) || first != nil && *first == 0 || last != nil && *last == 0 {
		if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
			if conn.TotalCount, err = a.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
		return conn, nil
	}

	if (after != nil || first != nil || before != nil || last != nil) && hasCollectedField(ctx, totalCountField) {
		count, err := a.Clone().Count(ctx)
		if err != nil {
			return nil, err
		}
		conn.TotalCount = count
	}

	a = pager.applyCursors(a, after, before)
	a = pager.applyOrder(a, last != nil)
	if limit := paginateLimit(first, last); limit != 0 {
		a.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := a.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}

	nodes, err := a.All(ctx)
	if err != nil || len(nodes) == 0 {
		return conn, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

var (
	// ArtistOrderFieldCreatedAt orders Artist by created_at.
	ArtistOrderFieldCreatedAt = &ArtistOrderField{
		field: artist.FieldCreatedAt,
		toCursor: func(a *Artist) Cursor {
			return Cursor{
				ID:    a.ID,
				Value: a.CreatedAt,
			}
		},
	}
)

// String implement fmt.Stringer interface.
func (f ArtistOrderField) String() string {
	var str string
	switch f.field {
	case artist.FieldCreatedAt:
		str = "CREATED_AT"
	}
	return str
}

// MarshalGQL implements graphql.Marshaler interface.
func (f ArtistOrderField) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(f.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (f *ArtistOrderField) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("ArtistOrderField %T must be a string", v)
	}
	switch str {
	case "CREATED_AT":
		*f = *ArtistOrderFieldCreatedAt
	default:
		return fmt.Errorf("%s is not a valid ArtistOrderField", str)
	}
	return nil
}

// ArtistOrderField defines the ordering field of Artist.
type ArtistOrderField struct {
	field    string
	toCursor func(*Artist) Cursor
}

// ArtistOrder defines the ordering of Artist.
type ArtistOrder struct {
	Direction OrderDirection    `json:"direction"`
	Field     *ArtistOrderField `json:"field"`
}

// DefaultArtistOrder is the default ordering of Artist.
var DefaultArtistOrder = &ArtistOrder{
	Direction: OrderDirectionAsc,
	Field: &ArtistOrderField{
		field: artist.FieldID,
		toCursor: func(a *Artist) Cursor {
			return Cursor{ID: a.ID}
		},
	},
}

// ToEdge converts Artist into ArtistEdge.
func (a *Artist) ToEdge(order *ArtistOrder) *ArtistEdge {
	if order == nil {
		order = DefaultArtistOrder
	}
	return &ArtistEdge{
		Node:   a,
		Cursor: order.Field.toCursor(a),
	}
}

// MenuEdge is the edge representation of Menu.
type MenuEdge struct {
	Node   *Menu  `json:"node"`
	Cursor Cursor `json:"cursor"`
}

// MenuConnection is the connection containing edges to Menu.
type MenuConnection struct {
	Edges      []*MenuEdge `json:"edges"`
	PageInfo   PageInfo    `json:"pageInfo"`
	TotalCount int         `json:"totalCount"`
}

func (c *MenuConnection) build(nodes []*Menu, pager *menuPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *Menu
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Menu {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Menu {
			return nodes[i]
		}
	}
	c.Edges = make([]*MenuEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &MenuEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// MenuPaginateOption enables pagination customization.
type MenuPaginateOption func(*menuPager) error

// WithMenuOrder configures pagination ordering.
func WithMenuOrder(order *MenuOrder) MenuPaginateOption {
	if order == nil {
		order = DefaultMenuOrder
	}
	o := *order
	return func(pager *menuPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultMenuOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithMenuFilter configures pagination filter.
func WithMenuFilter(filter func(*MenuQuery) (*MenuQuery, error)) MenuPaginateOption {
	return func(pager *menuPager) error {
		if filter == nil {
			return errors.New("MenuQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type menuPager struct {
	order  *MenuOrder
	filter func(*MenuQuery) (*MenuQuery, error)
}

func newMenuPager(opts []MenuPaginateOption) (*menuPager, error) {
	pager := &menuPager{}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultMenuOrder
	}
	return pager, nil
}

func (p *menuPager) applyFilter(query *MenuQuery) (*MenuQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *menuPager) toCursor(m *Menu) Cursor {
	return p.order.Field.toCursor(m)
}

func (p *menuPager) applyCursors(query *MenuQuery, after, before *Cursor) *MenuQuery {
	for _, predicate := range cursorsToPredicates(
		p.order.Direction, after, before,
		p.order.Field.field, DefaultMenuOrder.Field.field,
	) {
		query = query.Where(predicate)
	}
	return query
}

func (p *menuPager) applyOrder(query *MenuQuery, reverse bool) *MenuQuery {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	query = query.Order(direction.orderFunc(p.order.Field.field))
	if p.order.Field != DefaultMenuOrder.Field {
		query = query.Order(direction.orderFunc(DefaultMenuOrder.Field.field))
	}
	return query
}

func (p *menuPager) orderExpr(reverse bool) sql.Querier {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.field).Pad().WriteString(string(direction))
		if p.order.Field != DefaultMenuOrder.Field {
			b.Comma().Ident(DefaultMenuOrder.Field.field).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to Menu.
func (m *MenuQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...MenuPaginateOption,
) (*MenuConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newMenuPager(opts)
	if err != nil {
		return nil, err
	}
	if m, err = pager.applyFilter(m); err != nil {
		return nil, err
	}
	conn := &MenuConnection{Edges: []*MenuEdge{}}
	if !hasCollectedField(ctx, edgesField) || first != nil && *first == 0 || last != nil && *last == 0 {
		if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
			if conn.TotalCount, err = m.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
		return conn, nil
	}

	if (after != nil || first != nil || before != nil || last != nil) && hasCollectedField(ctx, totalCountField) {
		count, err := m.Clone().Count(ctx)
		if err != nil {
			return nil, err
		}
		conn.TotalCount = count
	}

	m = pager.applyCursors(m, after, before)
	m = pager.applyOrder(m, last != nil)
	if limit := paginateLimit(first, last); limit != 0 {
		m.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := m.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}

	nodes, err := m.All(ctx)
	if err != nil || len(nodes) == 0 {
		return conn, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// MenuOrderField defines the ordering field of Menu.
type MenuOrderField struct {
	field    string
	toCursor func(*Menu) Cursor
}

// MenuOrder defines the ordering of Menu.
type MenuOrder struct {
	Direction OrderDirection  `json:"direction"`
	Field     *MenuOrderField `json:"field"`
}

// DefaultMenuOrder is the default ordering of Menu.
var DefaultMenuOrder = &MenuOrder{
	Direction: OrderDirectionAsc,
	Field: &MenuOrderField{
		field: menu.FieldID,
		toCursor: func(m *Menu) Cursor {
			return Cursor{ID: m.ID}
		},
	},
}

// ToEdge converts Menu into MenuEdge.
func (m *Menu) ToEdge(order *MenuOrder) *MenuEdge {
	if order == nil {
		order = DefaultMenuOrder
	}
	return &MenuEdge{
		Node:   m,
		Cursor: order.Field.toCursor(m),
	}
}

// PartnershipEdge is the edge representation of Partnership.
type PartnershipEdge struct {
	Node   *Partnership `json:"node"`
	Cursor Cursor       `json:"cursor"`
}

// PartnershipConnection is the connection containing edges to Partnership.
type PartnershipConnection struct {
	Edges      []*PartnershipEdge `json:"edges"`
	PageInfo   PageInfo           `json:"pageInfo"`
	TotalCount int                `json:"totalCount"`
}

func (c *PartnershipConnection) build(nodes []*Partnership, pager *partnershipPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *Partnership
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Partnership {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Partnership {
			return nodes[i]
		}
	}
	c.Edges = make([]*PartnershipEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &PartnershipEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// PartnershipPaginateOption enables pagination customization.
type PartnershipPaginateOption func(*partnershipPager) error

// WithPartnershipOrder configures pagination ordering.
func WithPartnershipOrder(order *PartnershipOrder) PartnershipPaginateOption {
	if order == nil {
		order = DefaultPartnershipOrder
	}
	o := *order
	return func(pager *partnershipPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultPartnershipOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithPartnershipFilter configures pagination filter.
func WithPartnershipFilter(filter func(*PartnershipQuery) (*PartnershipQuery, error)) PartnershipPaginateOption {
	return func(pager *partnershipPager) error {
		if filter == nil {
			return errors.New("PartnershipQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type partnershipPager struct {
	order  *PartnershipOrder
	filter func(*PartnershipQuery) (*PartnershipQuery, error)
}

func newPartnershipPager(opts []PartnershipPaginateOption) (*partnershipPager, error) {
	pager := &partnershipPager{}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultPartnershipOrder
	}
	return pager, nil
}

func (p *partnershipPager) applyFilter(query *PartnershipQuery) (*PartnershipQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *partnershipPager) toCursor(pa *Partnership) Cursor {
	return p.order.Field.toCursor(pa)
}

func (p *partnershipPager) applyCursors(query *PartnershipQuery, after, before *Cursor) *PartnershipQuery {
	for _, predicate := range cursorsToPredicates(
		p.order.Direction, after, before,
		p.order.Field.field, DefaultPartnershipOrder.Field.field,
	) {
		query = query.Where(predicate)
	}
	return query
}

func (p *partnershipPager) applyOrder(query *PartnershipQuery, reverse bool) *PartnershipQuery {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	query = query.Order(direction.orderFunc(p.order.Field.field))
	if p.order.Field != DefaultPartnershipOrder.Field {
		query = query.Order(direction.orderFunc(DefaultPartnershipOrder.Field.field))
	}
	return query
}

func (p *partnershipPager) orderExpr(reverse bool) sql.Querier {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.field).Pad().WriteString(string(direction))
		if p.order.Field != DefaultPartnershipOrder.Field {
			b.Comma().Ident(DefaultPartnershipOrder.Field.field).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to Partnership.
func (pa *PartnershipQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...PartnershipPaginateOption,
) (*PartnershipConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newPartnershipPager(opts)
	if err != nil {
		return nil, err
	}
	if pa, err = pager.applyFilter(pa); err != nil {
		return nil, err
	}
	conn := &PartnershipConnection{Edges: []*PartnershipEdge{}}
	if !hasCollectedField(ctx, edgesField) || first != nil && *first == 0 || last != nil && *last == 0 {
		if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
			if conn.TotalCount, err = pa.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
		return conn, nil
	}

	if (after != nil || first != nil || before != nil || last != nil) && hasCollectedField(ctx, totalCountField) {
		count, err := pa.Clone().Count(ctx)
		if err != nil {
			return nil, err
		}
		conn.TotalCount = count
	}

	pa = pager.applyCursors(pa, after, before)
	pa = pager.applyOrder(pa, last != nil)
	if limit := paginateLimit(first, last); limit != 0 {
		pa.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := pa.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}

	nodes, err := pa.All(ctx)
	if err != nil || len(nodes) == 0 {
		return conn, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// PartnershipOrderField defines the ordering field of Partnership.
type PartnershipOrderField struct {
	field    string
	toCursor func(*Partnership) Cursor
}

// PartnershipOrder defines the ordering of Partnership.
type PartnershipOrder struct {
	Direction OrderDirection         `json:"direction"`
	Field     *PartnershipOrderField `json:"field"`
}

// DefaultPartnershipOrder is the default ordering of Partnership.
var DefaultPartnershipOrder = &PartnershipOrder{
	Direction: OrderDirectionAsc,
	Field: &PartnershipOrderField{
		field: partnership.FieldID,
		toCursor: func(pa *Partnership) Cursor {
			return Cursor{ID: pa.ID}
		},
	},
}

// ToEdge converts Partnership into PartnershipEdge.
func (pa *Partnership) ToEdge(order *PartnershipOrder) *PartnershipEdge {
	if order == nil {
		order = DefaultPartnershipOrder
	}
	return &PartnershipEdge{
		Node:   pa,
		Cursor: order.Field.toCursor(pa),
	}
}

// StoreEdge is the edge representation of Store.
type StoreEdge struct {
	Node   *Store `json:"node"`
	Cursor Cursor `json:"cursor"`
}

// StoreConnection is the connection containing edges to Store.
type StoreConnection struct {
	Edges      []*StoreEdge `json:"edges"`
	PageInfo   PageInfo     `json:"pageInfo"`
	TotalCount int          `json:"totalCount"`
}

func (c *StoreConnection) build(nodes []*Store, pager *storePager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *Store
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Store {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Store {
			return nodes[i]
		}
	}
	c.Edges = make([]*StoreEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &StoreEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// StorePaginateOption enables pagination customization.
type StorePaginateOption func(*storePager) error

// WithStoreOrder configures pagination ordering.
func WithStoreOrder(order *StoreOrder) StorePaginateOption {
	if order == nil {
		order = DefaultStoreOrder
	}
	o := *order
	return func(pager *storePager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultStoreOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithStoreFilter configures pagination filter.
func WithStoreFilter(filter func(*StoreQuery) (*StoreQuery, error)) StorePaginateOption {
	return func(pager *storePager) error {
		if filter == nil {
			return errors.New("StoreQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type storePager struct {
	order  *StoreOrder
	filter func(*StoreQuery) (*StoreQuery, error)
}

func newStorePager(opts []StorePaginateOption) (*storePager, error) {
	pager := &storePager{}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultStoreOrder
	}
	return pager, nil
}

func (p *storePager) applyFilter(query *StoreQuery) (*StoreQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *storePager) toCursor(s *Store) Cursor {
	return p.order.Field.toCursor(s)
}

func (p *storePager) applyCursors(query *StoreQuery, after, before *Cursor) *StoreQuery {
	for _, predicate := range cursorsToPredicates(
		p.order.Direction, after, before,
		p.order.Field.field, DefaultStoreOrder.Field.field,
	) {
		query = query.Where(predicate)
	}
	return query
}

func (p *storePager) applyOrder(query *StoreQuery, reverse bool) *StoreQuery {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	query = query.Order(direction.orderFunc(p.order.Field.field))
	if p.order.Field != DefaultStoreOrder.Field {
		query = query.Order(direction.orderFunc(DefaultStoreOrder.Field.field))
	}
	return query
}

func (p *storePager) orderExpr(reverse bool) sql.Querier {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.field).Pad().WriteString(string(direction))
		if p.order.Field != DefaultStoreOrder.Field {
			b.Comma().Ident(DefaultStoreOrder.Field.field).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to Store.
func (s *StoreQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...StorePaginateOption,
) (*StoreConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newStorePager(opts)
	if err != nil {
		return nil, err
	}
	if s, err = pager.applyFilter(s); err != nil {
		return nil, err
	}
	conn := &StoreConnection{Edges: []*StoreEdge{}}
	if !hasCollectedField(ctx, edgesField) || first != nil && *first == 0 || last != nil && *last == 0 {
		if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
			if conn.TotalCount, err = s.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
		return conn, nil
	}

	if (after != nil || first != nil || before != nil || last != nil) && hasCollectedField(ctx, totalCountField) {
		count, err := s.Clone().Count(ctx)
		if err != nil {
			return nil, err
		}
		conn.TotalCount = count
	}

	s = pager.applyCursors(s, after, before)
	s = pager.applyOrder(s, last != nil)
	if limit := paginateLimit(first, last); limit != 0 {
		s.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := s.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}

	nodes, err := s.All(ctx)
	if err != nil || len(nodes) == 0 {
		return conn, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// StoreOrderField defines the ordering field of Store.
type StoreOrderField struct {
	field    string
	toCursor func(*Store) Cursor
}

// StoreOrder defines the ordering of Store.
type StoreOrder struct {
	Direction OrderDirection   `json:"direction"`
	Field     *StoreOrderField `json:"field"`
}

// DefaultStoreOrder is the default ordering of Store.
var DefaultStoreOrder = &StoreOrder{
	Direction: OrderDirectionAsc,
	Field: &StoreOrderField{
		field: store.FieldID,
		toCursor: func(s *Store) Cursor {
			return Cursor{ID: s.ID}
		},
	},
}

// ToEdge converts Store into StoreEdge.
func (s *Store) ToEdge(order *StoreOrder) *StoreEdge {
	if order == nil {
		order = DefaultStoreOrder
	}
	return &StoreEdge{
		Node:   s,
		Cursor: order.Field.toCursor(s),
	}
}

// UserEdge is the edge representation of User.
type UserEdge struct {
	Node   *User  `json:"node"`
	Cursor Cursor `json:"cursor"`
}

// UserConnection is the connection containing edges to User.
type UserConnection struct {
	Edges      []*UserEdge `json:"edges"`
	PageInfo   PageInfo    `json:"pageInfo"`
	TotalCount int         `json:"totalCount"`
}

func (c *UserConnection) build(nodes []*User, pager *userPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *User
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *User {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *User {
			return nodes[i]
		}
	}
	c.Edges = make([]*UserEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &UserEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// UserPaginateOption enables pagination customization.
type UserPaginateOption func(*userPager) error

// WithUserOrder configures pagination ordering.
func WithUserOrder(order *UserOrder) UserPaginateOption {
	if order == nil {
		order = DefaultUserOrder
	}
	o := *order
	return func(pager *userPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultUserOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithUserFilter configures pagination filter.
func WithUserFilter(filter func(*UserQuery) (*UserQuery, error)) UserPaginateOption {
	return func(pager *userPager) error {
		if filter == nil {
			return errors.New("UserQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type userPager struct {
	order  *UserOrder
	filter func(*UserQuery) (*UserQuery, error)
}

func newUserPager(opts []UserPaginateOption) (*userPager, error) {
	pager := &userPager{}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultUserOrder
	}
	return pager, nil
}

func (p *userPager) applyFilter(query *UserQuery) (*UserQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *userPager) toCursor(u *User) Cursor {
	return p.order.Field.toCursor(u)
}

func (p *userPager) applyCursors(query *UserQuery, after, before *Cursor) *UserQuery {
	for _, predicate := range cursorsToPredicates(
		p.order.Direction, after, before,
		p.order.Field.field, DefaultUserOrder.Field.field,
	) {
		query = query.Where(predicate)
	}
	return query
}

func (p *userPager) applyOrder(query *UserQuery, reverse bool) *UserQuery {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	query = query.Order(direction.orderFunc(p.order.Field.field))
	if p.order.Field != DefaultUserOrder.Field {
		query = query.Order(direction.orderFunc(DefaultUserOrder.Field.field))
	}
	return query
}

func (p *userPager) orderExpr(reverse bool) sql.Querier {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.field).Pad().WriteString(string(direction))
		if p.order.Field != DefaultUserOrder.Field {
			b.Comma().Ident(DefaultUserOrder.Field.field).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to User.
func (u *UserQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...UserPaginateOption,
) (*UserConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newUserPager(opts)
	if err != nil {
		return nil, err
	}
	if u, err = pager.applyFilter(u); err != nil {
		return nil, err
	}
	conn := &UserConnection{Edges: []*UserEdge{}}
	if !hasCollectedField(ctx, edgesField) || first != nil && *first == 0 || last != nil && *last == 0 {
		if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
			if conn.TotalCount, err = u.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
		return conn, nil
	}

	if (after != nil || first != nil || before != nil || last != nil) && hasCollectedField(ctx, totalCountField) {
		count, err := u.Clone().Count(ctx)
		if err != nil {
			return nil, err
		}
		conn.TotalCount = count
	}

	u = pager.applyCursors(u, after, before)
	u = pager.applyOrder(u, last != nil)
	if limit := paginateLimit(first, last); limit != 0 {
		u.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := u.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}

	nodes, err := u.All(ctx)
	if err != nil || len(nodes) == 0 {
		return conn, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// UserOrderField defines the ordering field of User.
type UserOrderField struct {
	field    string
	toCursor func(*User) Cursor
}

// UserOrder defines the ordering of User.
type UserOrder struct {
	Direction OrderDirection  `json:"direction"`
	Field     *UserOrderField `json:"field"`
}

// DefaultUserOrder is the default ordering of User.
var DefaultUserOrder = &UserOrder{
	Direction: OrderDirectionAsc,
	Field: &UserOrderField{
		field: user.FieldID,
		toCursor: func(u *User) Cursor {
			return Cursor{ID: u.ID}
		},
	},
}

// ToEdge converts User into UserEdge.
func (u *User) ToEdge(order *UserOrder) *UserEdge {
	if order == nil {
		order = DefaultUserOrder
	}
	return &UserEdge{
		Node:   u,
		Cursor: order.Field.toCursor(u),
	}
}
