// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"odin/ent/partnership"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PartnershipCreate is the builder for creating a Partnership entity.
type PartnershipCreate struct {
	config
	mutation *PartnershipMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (pc *PartnershipCreate) SetName(s string) *PartnershipCreate {
	pc.mutation.SetName(s)
	return pc
}

// SetCompany sets the "company" field.
func (pc *PartnershipCreate) SetCompany(s string) *PartnershipCreate {
	pc.mutation.SetCompany(s)
	return pc
}

// SetEmail sets the "email" field.
func (pc *PartnershipCreate) SetEmail(s string) *PartnershipCreate {
	pc.mutation.SetEmail(s)
	return pc
}

// SetContent sets the "content" field.
func (pc *PartnershipCreate) SetContent(s string) *PartnershipCreate {
	pc.mutation.SetContent(s)
	return pc
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (pc *PartnershipCreate) SetNillableContent(s *string) *PartnershipCreate {
	if s != nil {
		pc.SetContent(*s)
	}
	return pc
}

// SetCreatedAt sets the "created_at" field.
func (pc *PartnershipCreate) SetCreatedAt(t time.Time) *PartnershipCreate {
	pc.mutation.SetCreatedAt(t)
	return pc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pc *PartnershipCreate) SetNillableCreatedAt(t *time.Time) *PartnershipCreate {
	if t != nil {
		pc.SetCreatedAt(*t)
	}
	return pc
}

// Mutation returns the PartnershipMutation object of the builder.
func (pc *PartnershipCreate) Mutation() *PartnershipMutation {
	return pc.mutation
}

// Save creates the Partnership in the database.
func (pc *PartnershipCreate) Save(ctx context.Context) (*Partnership, error) {
	var (
		err  error
		node *Partnership
	)
	pc.defaults()
	if len(pc.hooks) == 0 {
		if err = pc.check(); err != nil {
			return nil, err
		}
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PartnershipMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pc.check(); err != nil {
				return nil, err
			}
			pc.mutation = mutation
			if node, err = pc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			if pc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, pc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Partnership)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from PartnershipMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PartnershipCreate) SaveX(ctx context.Context) *Partnership {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PartnershipCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PartnershipCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pc *PartnershipCreate) defaults() {
	if _, ok := pc.mutation.Content(); !ok {
		v := partnership.DefaultContent
		pc.mutation.SetContent(v)
	}
	if _, ok := pc.mutation.CreatedAt(); !ok {
		v := partnership.DefaultCreatedAt()
		pc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PartnershipCreate) check() error {
	if _, ok := pc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Partnership.name"`)}
	}
	if v, ok := pc.mutation.Name(); ok {
		if err := partnership.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Partnership.name": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Company(); !ok {
		return &ValidationError{Name: "company", err: errors.New(`ent: missing required field "Partnership.company"`)}
	}
	if v, ok := pc.mutation.Company(); ok {
		if err := partnership.CompanyValidator(v); err != nil {
			return &ValidationError{Name: "company", err: fmt.Errorf(`ent: validator failed for field "Partnership.company": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Partnership.email"`)}
	}
	if v, ok := pc.mutation.Email(); ok {
		if err := partnership.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Partnership.email": %w`, err)}
		}
	}
	if _, ok := pc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Partnership.created_at"`)}
	}
	return nil
}

func (pc *PartnershipCreate) sqlSave(ctx context.Context) (*Partnership, error) {
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (pc *PartnershipCreate) createSpec() (*Partnership, *sqlgraph.CreateSpec) {
	var (
		_node = &Partnership{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: partnership.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: partnership.FieldID,
			},
		}
	)
	if value, ok := pc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: partnership.FieldName,
		})
		_node.Name = value
	}
	if value, ok := pc.mutation.Company(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: partnership.FieldCompany,
		})
		_node.Company = value
	}
	if value, ok := pc.mutation.Email(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: partnership.FieldEmail,
		})
		_node.Email = value
	}
	if value, ok := pc.mutation.Content(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: partnership.FieldContent,
		})
		_node.Content = value
	}
	if value, ok := pc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: partnership.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	return _node, _spec
}

// PartnershipCreateBulk is the builder for creating many Partnership entities in bulk.
type PartnershipCreateBulk struct {
	config
	builders []*PartnershipCreate
}

// Save creates the Partnership entities in the database.
func (pcb *PartnershipCreateBulk) Save(ctx context.Context) ([]*Partnership, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Partnership, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PartnershipMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PartnershipCreateBulk) SaveX(ctx context.Context) []*Partnership {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PartnershipCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PartnershipCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
