// Code generated by entc, DO NOT EDIT.

package artist

import (
	"time"
)

const (
	// Label holds the string label denoting the artist type in the database.
	Label = "artist"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldExternalURL holds the string denoting the external_url field in the database.
	FieldExternalURL = "external_url"
	// FieldPhoneNumber holds the string denoting the phone_number field in the database.
	FieldPhoneNumber = "phone_number"
	// FieldDiscord holds the string denoting the discord field in the database.
	FieldDiscord = "discord"
	// FieldRecommender holds the string denoting the recommender field in the database.
	FieldRecommender = "recommender"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the artist in the database.
	Table = "artists"
)

// Columns holds all SQL columns for artist fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldExternalURL,
	FieldPhoneNumber,
	FieldDiscord,
	FieldRecommender,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// ExternalURLValidator is a validator for the "external_url" field. It is called by the builders before save.
	ExternalURLValidator func(string) error
	// PhoneNumberValidator is a validator for the "phone_number" field. It is called by the builders before save.
	PhoneNumberValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)
