// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Member struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Nick   string `json:"nick"`
	Team   string `json:"team"`
	Detail string `json:"detail"`
	Img    string `json:"img"`
}

type NewMember struct {
	Name   string `json:"name"`
	Nick   string `json:"nick"`
	Team   string `json:"team"`
	Detail string `json:"detail"`
	Img    string `json:"img"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
