// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Artist is the predicate function for artist builders.
type Artist func(*sql.Selector)

// Menu is the predicate function for menu builders.
type Menu func(*sql.Selector)

// Partnership is the predicate function for partnership builders.
type Partnership func(*sql.Selector)

// Store is the predicate function for store builders.
type Store func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
