// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type ArtistInput struct {
	ID          *int    `json:"id"`
	Name        string  `json:"name"`
	ExternalURL string  `json:"externalUrl"`
	PhoneNumber string  `json:"phoneNumber"`
	Discord     *string `json:"discord"`
	Recommender *string `json:"recommender"`
}

type PartnershipInput struct {
	ID      *int    `json:"id"`
	Name    string  `json:"name"`
	Company string  `json:"company"`
	Email   string  `json:"email"`
	Content *string `json:"content"`
}

type StoreInput struct {
	ID       *int     `json:"id"`
	Name     string   `json:"name"`
	Food     []string `json:"food"`
	Location string   `json:"location"`
	OnFoot   *int     `json:"onFoot"`
}

type UserInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
